import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import pluginVue from 'eslint-plugin-vue';
import vueTsConfig from '@vue/eslint-config-typescript';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      'docs/.vitepress/dist/**',
      'docs/.vitepress/cache/**',
      // Generated by FormKit, ~100k of theme tokens — not hand-maintained.
      'formkit.theme.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  ...vueTsConfig(),

  {
    rules: {
      // The public API intentionally surfaces `any` in a few resolver/schema
      // seams where FormKit's own types bottom out. Surface these as warnings
      // so they stay visible without blocking CI.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Components are registered under their multi-word Craft* names via the
      // library entrypoint; SFC filenames are already the source of truth.
      'vue/multi-word-component-names': 'off',
    },
  },

  {
    // Build/docs scripts run in Node, not the browser bundle.
    files: [
      '*.config.{js,ts}',
      'docs/**/*.{js,ts}',
      'docs/.vitepress/**/*.{js,ts}',
    ],
    languageOptions: {
      globals: {
        __dirname: 'readonly',
        __filename: 'readonly',
        console: 'readonly',
        module: 'writable',
        process: 'readonly',
        require: 'readonly',
      },
    },
  },

  {
    files: ['tests/**/*.{ts,js,vue}'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    rules: {
      // Specs define small inline fixture components next to each test.
      'vue/one-component-per-file': 'off',
    },
  },
);
